apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    cont: frontend
spec:
  selector:
    cont: frontend
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
      protocol: TCP